// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpaMatch.Api.Data;

#nullable disable

namespace UpaMatch.Api.Migrations
{
    [DbContext(typeof(UpaMatchDbContext))]
    [Migration("20260929170000_Descartes")]
    partial class Descartes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UpaMatch.Api.Models.Descarte", b =>
                {
                    b.Property<Guid>("DeUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("DeUsuarioId", "AUsuarioId");

                    b.HasIndex("AUsuarioId");

                    b.ToTable("Descartes", (string)null);
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Like", b =>
                {
                    b.Property<Guid>("DeUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsSuperLike")
                        .HasColumnType("bit");

                    b.HasKey("DeUsuarioId", "AUsuarioId");

                    b.HasIndex("AUsuarioId");

                    b.ToTable("Likes", (string)null);
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Mascota", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Mascotas", (string)null);
                });

            modelBuilder.Entity("UpaMatch.Api.Models.MascotaInteres", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Interes")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId", "Interes");

                    b.ToTable("MascotaIntereses", (string)null);
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Descarte", b =>
                {
                    b.HasOne("UpaMatch.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpaMatch.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Like", b =>
                {
                    b.HasOne("UpaMatch.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpaMatch.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DeUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Mascota", b =>
                {
                    b.HasOne("UpaMatch.Api.Models.Usuario", "Usuario")
                        .WithOne("Mascota")
                        .HasForeignKey("UpaMatch.Api.Models.Mascota", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UpaMatch.Api.Models.MascotaInteres", b =>
                {
                    b.HasOne("UpaMatch.Api.Models.Mascota", null)
                        .WithMany("Intereses")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Mascota", b =>
                {
                    b.Navigation("Intereses");
                });

            modelBuilder.Entity("UpaMatch.Api.Models.Usuario", b =>
                {
                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
